export const tagTypes = {
  auth: "Auth",
  users: "User",
  profile: "Profile",
  announcements: "Announcements",
  events: "Events",
  content: "content",
  categories: "categories",
  experience: "experience",
  otherTask: "otherTask",
  faq: "faq",
  booking: "booking",
  dashboard: "dashboard",
  verification: "verification",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.users,
  tagTypes.profile,
  tagTypes.announcements,
  tagTypes.events,
  tagTypes.content,
  tagTypes.categories,
  tagTypes.experience,
  tagTypes.otherTask,
  tagTypes.faq,
  tagTypes.booking,
  tagTypes.dashboard,
  tagTypes.verification,
];
